### ISSUE TITLE
Add Archlinux support

### ISSUE THREAD

**Issue by Oxalin** [suaefar/ryzen-test#16]
Archlinux uses pacman instead of dnf and apt-get. The script exits when it tries to install required development packages.

**Comment by Oxalin** [comment]
Here is the required patch

[0001-Add-Archlinux-support.patch.txt](https://github.com/suaefar/ryzen-test/files/1353305/0001-Add-Archlinux-support.patch.txt)

**Comment by Oxalin** [comment]
If you prefer that I fork the code and go through a pull request, let me know.

**Comment by suaefar** [comment]
Arch linux is not supported because gcc-7.1 did not compile with the provided gcc version.
Even if it does now, it can change any day in the future.
Support for a rolling release distro is not feasible.
The most important thing for me is if you tested the patch on Arch and if runs correctly.
If 2x yes, I can apply the patch but I won't mention Arch in the readme.

**Comment by jbax** [comment]
Just letting you know that patch works for me on Manjaro Linux. Thanks @Oxalin!

**Comment by Oxalin** [comment]
I'll have to send a new version though, there shouldn't be a "abs" in the package list.

**Comment by Oxalin** [comment]
This would be the correct patch.

[0001-Add-Archlinux-support.patch.txt](https://github.com/suaefar/ryzen-test/files/1363968/0001-Add-Archlinux-support.patch.txt)

Tested on my setup on ArchLinux and I was able to confirm my CPU is also concerned by the segfault error... RMA has been approved by AMD.

**Comment by suaefar** [comment]
Okay, added the line.
